name: CI

on:
  push:
    branches: [ main ]
  
  pull_request:
    types: [ closed ]
    branches: [ main ]
  
jobs:
  update-lambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update lambda function
        run: ${GITHUB_WORKSPACE}/.github/update.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
