name: CI

on:
  push:
    branches: [ main ]
  
  pull_request:
    types: [ closed ]
    branches: [ main ]
  
jobs:
  update-lambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update lambda function
        run: ${GITHUB_WORKSPACE}/update.sh
